default:
	clang -Wall -Wpedantic -Wextra -Werror mbsh.c -o mbsh
debug:
	clang -Wall -Wpedantic -Wextra mbsh.c -o mbsh -g
full:
	clang -Wall -Wpedantic -Werror -Wextra mbsh.c -o mbsh
clean:
	rm -f mbsh